### ISSUE TITLE
Update LPC Directive Static Graphics

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#326]

**Comment by helencarey** [comment]
Draft 1 should:
- [ ] add the THREEjs plugins for loading & parsing svg
- [ ] troubleshoot the new assets, and make sure they properly convert to meshes
- [ ] wire it together (somehow) in the lpcRenderer script

**Comment by helencarey** [comment]
**1.) adds the THREEjs plugins for loading & parsing svg**
- @starakaj not sure where these should go. Currently they are in common-components/lpc-directive/THREEjs-plugins. AFIF, these aren’t bower-able repos. The svg-loader is a two.js port. The official THREE repo has [this script in the examples directory](https://github.com/mrdoob/three.js/blob/master/examples/js/loaders/SVGLoader.js), but they haven’t incorporated it into the THREEjs dist releases yet. 

- I have not tried it, but someone posted this : https://www.npmjs.com/package/three-svg-loader

- Our bridge script is ‘svgLoaderToMesh.js.’  At the moment it's just a global function that gets called from each of the files in common-components/lpc-directive/meshes.

**Comment by helencarey** [comment]
**2.)  adds the new, parser-ready svg assets**
- squeaky-clean svgs used by the lpc-directive are in img/lpcDir/
- if an svg won’t load: 
  - make sure you are using only closed paths or shape primitives
  - make sure each node is positioned relative to the viewbox attr. The loader often errs with transform attrs.

**Comment by helencarey** [comment]
**3.) enables conversion of new svg assets to meshes**

yeah, this works, but not as well as I want it to -- the shape-mesh groups currently aren't responsive

In theory, the shape-mesh groups should scale with the dimensions of the lpc-dir parent element ( onResize handler is in the controller animate() ). In reality, i think something about our page loading + redrawing process complicates this. (This is probably fixable by learning a little more about [matrix transforms in THREE](https://threejs.org/docs/#manual/en/introduction/Matrix-transformations).)

Also, in reality, _it may not matter_. We only load the BeachScene static assets at 1 known dimension ( full-width, row-h * 4 ), so currently I’m not scaling them at all.

**Comment by helencarey** [comment]
**4.) update the lpcRenderer**

- I really wanted to get the mesh creation code out of the lpcRender -- like, I wanted revisable designer-friendly mesh scripts to be separate from the lpcRender config, which is something I’m more likely to mess up. I wasn’t sure what the proper angular 1x-esque way to do this -- (like, what is a ‘provider’?) I ended up just copying what you did in the three-drawing.js to get an object into the directive scope), so this:
```
var lpcDirective = angular.module('lpcDirective');
lpcDirective.value('Mesh', new Mesh());
```

- The lpcRenderer helper objects (Draw, Materials, Meshes) are in lpc-direct/renderer-scripts. @starakaj Lmk I should do this differently.

---------

**todo**: only draw the beachScene where appropriate (freePlay, questBF)
**todo**: draw the bare, responsive wave everywhere else ( tutorial, profiles/settings)

**Comment by helencarey** [comment]
**5.) update the lpc-directive controller**

**todo:** make sure touch interactions are working
**todo:** uncomment the wave, and troubleshoot as needed

**Comment by helencarey** [comment]
Hey @starakaj,
The branch, hmc/lpc-directive-beachScene, essentially does everything that it needs to do. 
EXCEPT for 2 things:
- [ ]  1.) A potential issue with saving the user’s Target F3 after moving the slider. 
- [ ] 2.) An issue with drawing the wave with data from the AudioPlugin.

Any chance we could touch base about these next week?
I'll leave details below.

**Comment by helencarey** [comment]
@starakaj 
branch: hmc/lpc-directive-beachScene
**ISSUE 1:  Saving User-Placed Target F3s**
  
In the lpc-directive_controller, we are updating the user’s Target F3 via the ProfileService onTouchMove. This creates creates a LOT of fb 400 errors (client error)
<img width="1343" alt="screen shot 2019-03-07 at 4 42 35 pm" src="https://user-images.githubusercontent.com/8650944/53992045-dcfb4580-40f9-11e9-85f4-cc9eb7d48806.png">

In the current branch this code is at lines 338-341.
Its called from the animate loop (60fps) when targetNeedsUpdate is true (trigger = slider onTouchMove), so maybe we are just be slamming the ProfileService/firebase with data.

When I moved the code to be triggered by the slider’s onTouchEnd (ln 226-232), I got fewer errors - sometimes no errs; but I’m not sure if we are saving 100% of the time. (Often the value would reset when I navigated to another page and back.)

**My questions are: What is this process supposed to do, like what is the end goal? 
And what should I test for?**

Do we just need to save the last slider location before the user ends the session? (save ui state)
Is this intended as an ‘undo btn’ in case someone accidentally moves the slider?
Or is this an important piece of session data, like we need a saved record of where the slider was to match w/ audio or rating timestamps?


n.b. These fb errors would happen before I started working on this branch, so maybe they aren't actually indicative of a problem, the transactions will eventually complete, and everything is totally fine. 

anyway, pls advise.

**Comment by helencarey** [comment]
@starakaj
branch: hmc/lpc-directive-beachScene
**ISSUE 2: Drawing the wave with AudioPlugin data.**

_wave with Audio Plugin data_
![simulator screen shot - ipad air - 2019-03-07 at 15 12 03](https://user-images.githubusercontent.com/8650944/53993239-d4583e80-40fc-11e9-8999-c6c00d100f2c.png)

_wave without Audio Plugin data_
![simulator screen shot - ipad air - 2019-03-07 at 15 14 02](https://user-images.githubusercontent.com/8650944/53993284-f0f47680-40fc-11e9-8840-3d193bb86e8e.png)

Not sure what’s causing this. 
It only happens when there is AudioPlugin data in Free Play and Quest. (beachScene)
The wave stays within its container w/ plugin data in Profiles/Settings and Tutorial, as usual.
The wave is drawn with the same code for all instances (AudioPlugin vs no audio, free play vs quest vs tutorial, etc), so it must not be reading my wave container dimensions in the new scene.

In all instances, the wave responds correctly; it makes correct /r/ shapes. 
It just draws at like 2x the size in the new Free Play and Quest scene.

Any thoughts?
Is this a retina thing? 
I believe all the webGL stuff is drawn at 1:1, and cordova adjusts the logical coordinate space into whatever device scale factor it needs. Right?

**Comment by helencarey** [comment]
This update deals with the way we draw and layer our beach scene graphics, as documented above. I've put the relevant QA checkpoints in tickets #242 and #331.
