### ISSUE TITLE
Add badges logic to highscores & saving

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#357]
on branch anyonecanresume-with-highscores

**TODO**
- [x] implement logic
- [x] add 'uncleaned' svg
- [x] test logic

**Comment by helencarey** [comment]
### QA Checkpoints
**changes affect:** Quest

**‘On A Roll!’ Badge**
- [ ] should appear on the 3 consecutive gold rating
- [ ] should disappear as soon as the streak is broken

**’New Record!’ Badge**
- [ ] should appear whenever a milestone is reached (hsib, mgib, hsiq, mgiq, streak), and it should remain on the screen until the end of each block 
- [ ] the newRecord badge clears properly at the end of each block 
- [ ] if the newRecord badge has been on screen for 1 trial and a ’onARoll’ event is triggered, the badges will switch — the only exceptions to this are the block level milestones: hsib & mgib 
- [ ] if the above sequences occurs and the badges switch, the newRecord badge will appear again when the streak is broken, as long as it is not cleared by the end of the block.

**VQA**
(branch should look like)

‘On A Roll!’ Badge
![Simulator Screen Shot - iPad (5th generation) - 2019-10-25 at 19 56 07](https://user-images.githubusercontent.com/8650944/67611136-8f554b00-f765-11e9-86ec-d4860113d96f.png)

’New Record!’ Badge
![Simulator Screen Shot - iPad (5th generation) - 2019-10-25 at 19 56 21](https://user-images.githubusercontent.com/8650944/67611140-a09e5780-f765-11e9-90bb-0faeca5b33c2.png)
