### ISSUE TITLE
qtDialog: Card Sequence (Logic)

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#423]
## hmc/qtDialog-endOfBlock-logic (branch)
last update: 12/06/19

### Main Procs (manipulate $scope objects)
............................
**on questRating(): _every trial_**
_purpose: update the $scope.scores_
1. coin graphic updated
2. scores counters updated
3. currentWordIdx is checked for end of block
   - scores.endOfBlock (T/F) is set
4. checkUpdateMilestones()

............................
**on checkUpdateMilestones() _every trial_**
_purpose: update the $scope.milestones & $scope.badges_
1. if a new milestone is achieved:
    - display an in-game badge, if appropriate
   - updateMilestoneRecord()
     _- updates record that is saved to fb on completion of quest_
   - updateMilestoneCard()
     - sets milestone achievement flags and data in $scope.badges for use in end-of-block cards
2. if (scores.endOfBlock)
   - performance (diff level) is calc'd #TODO
   - prepare progSum or endSum card data
   - prepEndOfBlock()

............................
**on prepEndOfBlock()**
_purpose: create an array of card templates based on the milestones achieved in the block and badges.qtDialog status_
1. card templates and milestone data for each flagged milestone achievement is read into badges.cardSeq
2. end cards ('feedback', score summaries, etc) are added to badges.cardSeq
3. nextCard();

............................
**on nextCard()**
_called by checkUpdateMilestones() or $scope.nextCard()_
_purpose: controls card display and user input_
1. populates badges.card object (used by html) with correct card in sequence
2. badges.qtDialog.isVisible = true;
3. on the dialog box is on screen the seq is advanced thru the 'Next' or 'Resume Quest' btns

**TODO:** 
- [x] figure out resume-quest proc
- [x] add sessionID back into fb Milestone record. Put it in controller endWordPractice().
- [x] make sure $scope.count is always a multiple of 10

**Comment by helencarey** [comment]
### QA Checkpoints

**Changes affect:** Quests

**Test:** Tests number of trials available to select on from the Quest Config Page.

**Note:** Most of the QA for this ticket has been covered by #487, #488, & #489  

**ToDo:** 
- Start an off-protocol Quest.
- On Quest Config Page, go to the Select Session Trial Goal slider
  - [ ] you should only be able to select a Trial Goal that is a multiple of 10 (range: 20-100 trials)
  - [ ] the minimum number of trials should = 20
