### ISSUE TITLE
QA Note: End-of-Quest Cards

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#488]
## QA Checkpoints

**Changes affect:** All Quest instances. End-of-Activity cards only appear in Quest.

**Purpose:** Tests that 2 optional cards (mgiq & hsiq) )and 2 required cards (endSummary& finalScore) are properly displayed when a Quest is finished.

**Note:** We will release branch internally only, so that the debug box can be displayed.

------------
## ToDo: 
Please start a Quest, and score the trials so that you achieve the milestones listed below. 
End-of-Quest cards only happen when a Quest is complete, so select like 20 trials.

### Most Gold in Quest (mgiq) Achievement Card
- [x] **display:** This will be displayed at the end of the Quest, _if_ you have exceeded your previously saved mgiq highscore.
- [x] **minimum threshold:** No minimum threshold. If you have no highscores, you will first earn this achievement after your 1st gold rating.
- [x] **data:** Should be the same as the value in the debug box.

### High Score in Quest (hsiq) Achievement Card
- [x] **display:** This will be displayed at the end of the Quest, _if_ you have exceeded your previously saved hsiq highscore.
- [x] **minimum threshold:** 20pts. You must earn at least 20pts in a Quest before this milestone will first be recorded. 
- [x] **data:** Should be the same as the value in the debug box.

### End-Summary Card
- [x] **display:** This card should always display at the end of the a Quest, and it should be the 2nd to last card in the end-of-quest card stack.
- [x] **data:** Card will always contain the total count of each type of coin earned in the Quest

### Final Score Card
- [x] **display:** This card should always display at the end of the a Quest, and it should be the last card in the end-of-quest card stack.
- [x] **data:** The card shows the user's final score. This should be the same as the value listed above the sand dollar.
- [x] **Close Btn:** Ends the Quest and returns the user to the Quest Menu Page.
