### ISSUE TITLE
QA Note: End-of-Block Cards

### ISSUE THREAD

**Issue by helencarey** [ByunLab/staRt-ionic#489]
## QA Checkpoints

**Changes affect:** All Quest instances. End-of-Block cards only appear in Quest.

**Purpose:**  Tests that the correct end-of-block cards appear after every 10 trials. Most end-of-block cards tell you about achievements that you have earned in the proceeding block.

**Note:** We will release branch internally only, so that the debug box can be displayed.
Scoring: gold = 3pts, silver = 2pts, bronze = 1pt

----------
## ToDo:
Please start a Quest, and score the trials so that you achieve the milestones listed below. 
(This test is just about making sure the end-of-block cards display and match the values in the debug box, so it doesn't matter what kind of Quest you do.)

### Most Gold in Block (mgib) Achievement Card
- [x] **display:** This card only displays if you earn a mgib.
- [x] **minimum threshold:** No minimum threshold. If you have no highscores, you will first earn this achievement after your 1st gold rating. 
- [x] **data:** The number on the achievement card should match the golds in the block.
- [x] **frequency:** You can earn this again the next time you exceed your current mgib score

### High Score in Block (hsib) Achievement Card 
- [x] **display:** This card only displays if you earn a hsib.
- [x] **minimum threshold:** Minimum threshold: 10pts. If you have no highscores, you will first earn this achievement after you score 11pts in a block.
- [x] **data:** The number on the achievement card should match the hsib value in the debug box 
- [x] **frequency:** You can earn this again the next time you exceed your current hsib score

### Streak (streak) Achievement Card
- **purpose:** achievement for most gold coins in-a-row
- [x] **display:** This card only displays if you exceed your current streak score by the end of the block. 
  If a new streak achievement is attained spanning 2 blocks, then the achievement card will show at the end of the 2nd block. (For example, say you get an 8-gold streak, where 5 golds are earned in block 1 and then 3 more golds are earned in block 2. The Streak Achievement Card will display at the end of block 2)
- [x] **minimum threshold:** 2 golds. If you have no highscores, you will first earn this achievement after you score 2 golds in a row.
- [x] **data:** The number on the achievement card should correctly match Streak the value in the debug box.
- [x] **frequency:** You can earn this achievement multiple times per Quest -- whenever you achieve a longer streak. 

### Perfect Block Achievement Card
- [x] **display:** This card only displays if you earn 10 golds in a block.
- [x] **minimum threshold:** None. Will display the first time you earn a Perfect Block
- [x] **data:** Counts the number of times you earn the achievement. The value should match the value in the debug box.
- [x] **frequency:** You can earn this achievement multiple times per Quest -- whenever you get a Perfect Block.

### Increasing Difficulty Notification Card
- [x] **display:** This card only displays if your performance in the previous block meets certain conditions.
- [x] **data:** No score, just a note to let you know that the difficulty is increasing.
- [x] **frequency:** You could earn it at the end of each block.

### Feedback Notification Card
- [x] **display:** This card displays at the end of every block, regardless of performance. It should always be the 2nd to last card.
- [x] **data:** No score, just a note to remind the SLP to provide feedback to the student.

### Progress Summary Notification Card
- [x] **display:** This card displays at the end of every block, except for the last block (end-of-quest). It should always be the last card.
- [x] **data:** Card will always contain the total count of each type of coin earned so far.
- [x]  Clicking 'Resume Quest' should close the end-of-block cards and resume the activity.

**Comment by yl5504** [comment]
@helencarey Sometimes the "Checkpoint" box - Feedback Notification Card would jump right to the last card before I could read it or click it.
[1576104578902339.mp4.zip](https://github.com/ByunLab/staRt-ionic/files/3952962/1576104578902339.mp4.zip)

**Comment by helencarey** [comment]
@yl5504 Thanks for sending the vid. 
 @WillHaack I haven't been able to reproduce this. I did not pause the wave draw loop when the dialog box comes up, should I start with that or do you think this is a touch trigger thing?

**Comment by WillHaack** [comment]
@helencarey I think it's related to the general bug of functions firing twice. (Double ratings, double "Would you like to leave the session?", etc.) I don't know exactly what causes the problem, but I don't think it's coming from your code specifically. So I suggest you don't address it until later when I've done some other attempts at fixing the source problem.
